import mongoose from 'mongoose';

const partySchema = new mongoose.Schema({
  name: { type: String, required: true },
  code: { type: String, unique: true, sparse: true },
  type: { type: String, enum: ['customer', 'distributor', 'super_stocker', 'supplier', 'visited'], required: true },
  group: String,
  roleRule: String,
  customFields: [{
    name: String,
    value: String,
  }],
  contactPerson: String,
  phone: String,
  email: String,
  status: { type: String, enum: ['active', 'inactive', 'blocked'], default: 'active' },
  region: String,
  gstin: String,
  pan: String,
  address: {
    street: String,
    city: String,
    state: String,
    pincode: String,
    country: { type: String, default: 'India' },
  },
  billingAddress: {
    street: String,
    city: String,
    state: String,
    pincode: String,
    country: { type: String, default: 'India' },
  },
  shippingAddress: {
    street: String,
    city: String,
    state: String,
    pincode: String,
    country: { type: String, default: 'India' },
  },
  geoLocation: {
    lat: Number,
    lng: Number,
  },
  openingBalance: { type: Number, default: 0 },
  openingBalanceType: { type: String, enum: ['to_collect', 'to_pay'], default: 'to_collect' },
  creditPeriod: { type: Number, default: 0 },
  creditLimit: { type: Number, default: 0 },
  creditBillLimit: { type: Number, default: 0 },
  sequence: { type: Number, default: 0 },
  mobileMandatory: { type: Boolean, default: false },
  ekycId: String,
  stateOfSupply: String,
  outstandingBalance: { type: Number, default: 0 },
  paymentTerms: { type: String, default: '30 days' },
  assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  route: { type: mongoose.Schema.Types.ObjectId, ref: 'Route' },
  priceList: { type: mongoose.Schema.Types.ObjectId, ref: 'PriceList' },
  isActive: { type: Boolean, default: true },
  notes: String,
  documents: [{
    name: String,
    type: String,
    url: String,
  }],
  accessDetails: {
    loginEnabled: { type: Boolean, default: false },
    portalRole: String,
    username: String,
  },
  loginEmail: { type: String, unique: true, sparse: true, lowercase: true },
  loginPassword: { type: String, select: false },
}, { timestamps: true });

export default mongoose.model('Party', partySchema);
